### ISSUE TITLE
Mixed content warnings

### ISSUE THREAD

**Issue by maurizi** [azavea/transit-analyst#39]
From the browser console:
> Blocked loading mixed active content “http://thehill.com/sites/all/themes/thehill/fonts/Graphik-Regular-Web.woff2”
> Blocked loading mixed active content “http://thehill.com/sites/all/themes/thehill/fonts/ChronicleDisp-Bold.otf”
> Blocked loading mixed active content “http://thehill.com/sites/all/themes/thehill/fonts/Graphik-Bold-Web.woff2”
> Blocked loading mixed active content “http://thehill.com/sites/all/themes/thehill/fonts/Graphik-Semibold-Web.woff2”

**Comment by flibbertigibbet** [comment]
Haven't been able to reproduce in Chrome/Linux

**Comment by maurizi** [comment]
Encountered on Firefox on Ubuntu

**Comment by flibbertigibbet** [comment]
Unable to reproduce on Firefox on Ubuntu. Further interaction required to see?

**Comment by flibbertigibbet** [comment]
Site definitely shouldn't be loading anything from that domain, in any case.

**Comment by maurizi** [comment]
Happens on page load for me. Possibly the failing fonts are a fallback, and you have the preferred font available but I don't?

![screenshot from 2018-01-04 12-23-16](https://user-images.githubusercontent.com/4432106/34575863-2006c6de-f14a-11e7-9ac5-aeffaa7a1ef3.png)

**Comment by flibbertigibbet** [comment]
Do you maybe have that site loaded in another tab or window? Unclear why anything for this site would load from that domain.

**Comment by maurizi** [comment]
I did have that site open in another tab... TIL you can get mixed content warnings from other tabs in the same browser :sob:
